language: vim

os:
  - linux
  # - osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vim  ; fi

script: |
  pwd
  make all
