language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
script: |
  ln -s ${PWD} ~/.vim
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  source vimrc
  VIMRC) -c 'Vader! test/*'
